### ISSUE TITLE
The sample code does not work

### ISSUE THREAD

**Issue by conanzxn** [hekailiang/squirrel#34] opened 2015-01-21 12:09 UTC
Hi,

I'm interested in this state machine framework. When I try to run the sample code with v0.3.6, it give me the following. Any ideas? Many thanks!

Exception in thread "main" org.squirrelframework.foundation.exception.SquirrelRuntimeException: 00010007 : couldn't construct new 'null' with args [fromAToB, org.squirrelframework.foundation.fsm.impl.ExecutionContext@305f849b].

**Comment by hekailiang** [comment] 2015-01-22 02:11
which sample does not work?

**Comment by conanzxn** [comment] 2015-01-22 09:46
Please find the code below.

```java
import org.squirrelframework.foundation.fsm.StateMachineBuilderFactory;
import org.squirrelframework.foundation.fsm.UntypedStateMachine;
import org.squirrelframework.foundation.fsm.UntypedStateMachineBuilder;
import org.squirrelframework.foundation.fsm.annotation.StateMachineParameters;
import org.squirrelframework.foundation.fsm.impl.AbstractUntypedStateMachine;


public class StandaloneStateMachineTest {
	 // 1. Define State Machine Event
    enum FSMEvent {
        ToA, ToB, ToC, ToD
    }

    // 2. Define State Machine Class
    @StateMachineParameters(stateType=String.class, eventType=FSMEvent.class, contextType=Integer.class)
    static class StateMachineSample extends AbstractUntypedStateMachine {
    	
    	StateMachineSample() {
    		
    	}
    	
        public void fromAToB(String from, String to, FSMEvent event, Integer context) {
            System.out.println("Transition from '"+from+"' to '"+to+"' on event '"+event+
                "' with context '"+context+"'.");
        }

        public void ontoB(String from, String to, FSMEvent event, Integer context) {
            System.out.println("Entry State \'"+to+"\'.");
        }
    }

    public static void main(String[] args) {
        // 3. Build State Transitions
        UntypedStateMachineBuilder builder = StateMachineBuilderFactory.create(StateMachineSample.class);
        builder.externalTransition().from("A").to("B").on(FSMEvent.ToB).callMethod("fromAToB");
        builder.onEntry("B").callMethod("ontoB");

        // 4. Use State Machine
        UntypedStateMachine fsm = builder.newStateMachine("A");
        fsm.fire(FSMEvent.ToB, 10);

        System.out.println("Current state is "+fsm.getCurrentState());
    }
}

**Comment by hekailiang** [comment] 2015-01-22 09:59
I do not have any problem to run your sample code. Everything works fine. And I cannot see why this simple code breaks. Any error stack information?

**Comment by conanzxn** [comment] 2015-01-22 12:50
I got the exception below when I run this.

Exception in thread "main" org.squirrelframework.foundation.exception.SquirrelRuntimeException: 00010007 : couldn't construct new 'null' with args [fromAToB, org.squirrelframework.foundation.fsm.impl.ExecutionContext@305f849].

**Comment by conanzxn** [comment] 2015-01-22 13:08
```
org.squirrelframework.foundation.exception.SquirrelRuntimeException: 00010007 : couldn't construct new 'null' with args [fromAToB, org.squirrelframework.foundation.fsm.impl.ExecutionContext@19fe59c2].
	at org.squirrelframework.foundation.util.ReflectUtils.newInstance(ReflectUtils.java:255)
	at org.squirrelframework.foundation.util.ReflectUtils.newInstance(ReflectUtils.java:228)
	at org.squirrelframework.foundation.component.SquirrelProvider.newInstance(SquirrelProvider.java:57)
	at org.squirrelframework.foundation.component.SquirrelProvider.newInstance(SquirrelProvider.java:38)
	at org.squirrelframework.foundation.fsm.impl.FSM.newMethodCallActionProxy(FSM.java:103)
	at org.squirrelframework.foundation.fsm.impl.TransitionBuilderImpl.callMethod(TransitionBuilderImpl.java:54)
```

**Comment by hekailiang** [comment] 2015-02-06 11:10
Since the issue cannot be produced and no other user report this problem. I will close this issue for now. If more information can be provided and can prove this is a bug, please reopen the issue.

**Closed by hekailiang** 2015-02-06 11:10 UTC

**Comment by himanshuvirmani** [comment] 2015-11-06 18:41
I am also getting the same error. Was this issue resolved/identified?

**Comment by winder** [comment] 2017-09-06 13:42
You get this same error if your StateMachine machine object constructor has an argument and you don't specify the argument type in `StateMachineBuilderFactory.create` or don't provide the argument in `newStateMachine`.

**Comment by hekailiang** [comment] 2017-12-07 04:58
`package org.squirrelframework.foundation.issues;

import org.squirrelframework.foundation.fsm.StateMachineBuilderFactory;
import org.squirrelframework.foundation.fsm.UntypedStateMachine;
import org.squirrelframework.foundation.fsm.UntypedStateMachineBuilder;
import org.squirrelframework.foundation.fsm.annotation.StateMachineParameters;
import org.squirrelframework.foundation.fsm.annotation.Transit;
import org.squirrelframework.foundation.fsm.annotation.Transitions;
import org.squirrelframework.foundation.fsm.impl.AbstractUntypedStateMachine;

public class IssueSample {
    enum TestEvent {
        toA, toB, toC, toD
    }

    @Transitions({
            @Transit(from="A", to="B", on="toB", callMethod="fromAToB"),
            @Transit(from="B", to="C", on="toC"),
            @Transit(from="C", to="D", on="toD")
    })

    @StateMachineParameters(stateType=String.class, eventType=TestEvent.class, contextType=Integer.class)
    static class UntypedStateMachineSample extends AbstractUntypedStateMachine {
        // No need to specify constructor anymore since 0.2.9
        // protected UntypedStateMachineSample(ImmutableUntypedState initialState,
        //  Map<Object, ImmutableUntypedState> states) {
        //    super(initialState, states);
        // }

        protected void fromAToB(String from, String to, TestEvent event, Integer context) {
            System.out.println("fromAToB");
        }

        protected void transitFromDToAOntoA(String from, String to, TestEvent event, Integer context) {
            // transition action still type safe ...
            System.out.println("transitFromDToAOntoA");
        }
    }

    public static void main(String[] args) {
        UntypedStateMachineBuilder builder = StateMachineBuilderFactory.create(
                UntypedStateMachineSample.class);
        // state machine builder not type safe anymore
        builder.externalTransition().from("D").to("A").on(TestEvent.toA);
        UntypedStateMachine fsm = builder.newStateMachine("A");
        fsm.fire(TestEvent.toB);
    }
}`
the sample code works as expected

**Comment by Louis012** [comment] 2017-12-07 09:20
yes, but I am refering to the example in the "Untyped state machine" section, which is not working for me.

Here it is : 

`enum TestEvent {
    toA, toB, toC, toD
}

@Transitions({
    @Transit(from="A", to="B", on="toB", callMethod="fromAToB"),
    @Transit(from="B", to="C", on="toC"),
    @Transit(from="C", to="D", on="toD")
})
@StateMachineParameters(stateType=String.class, eventType=TestEvent.class, contextType=Integer.class)
class UntypedStateMachineSample extends AbstractUntypedStateMachine {
    // No need to specify constructor anymore since 0.2.9
    // protected UntypedStateMachineSample(ImmutableUntypedState initialState,
    //  Map<Object, ImmutableUntypedState> states) {
    //    super(initialState, states);
    // }
    
    protected void fromAToB(String from, String to, TestEvent event, Integer context) {
        // transition action still type safe ...
    }

    protected void transitFromDToAOntoA(String from, String to, TestEvent event, Integer context) {
        // transition action still type safe ...
    }
}

UntypedStateMachineBuilder builder = StateMachineBuilderFactory.create(
    UntypedStateMachineSample.class);
// state machine builder not type safe anymore
builder.externalTransition().from("D").to("A").on(TestEvent.toA);
UntypedStateMachine fsm = builder.newStateMachine("A");`

**Comment by 18910949204** [comment] 2018-11-05 11:46
> yes, but I am refering to the example in the "Untyped state machine" section, which is not working for me.
> 
> Here it is :
> 
> ```
> enum TestEvent {
>      toA, toB, toC, toD
> }
> 
> @Transitions({
>     @Transit(from="A", to="B", on="toB", callMethod="fromAToB"),
>     @Transit(from="B", to="C", on="toC"),
>     @Transit(from="C", to="D", on="toD")
> })
> 
> @StateMachineParameters(stateType=String.class, eventType=TestEvent.class, contextType=Integer.class)
> class UntypedStateMachineSample extends AbstractUntypedStateMachine {
>     // No need to specify constructor anymore since 0.2.9
>     // protected UntypedStateMachineSample(ImmutableUntypedState initialState,
>     //  Map<Object, ImmutableUntypedState> states) {
>     //    super(initialState, states);
>     // }
> 
>     protected void fromAToB(String from, String to, TestEvent event, Integer context) {
>         // transition action still type safe ...
>     }
> 
>     protected void transitFromDToAOntoA(String from, String to, TestEvent event, Integer context) {
>         // transition action still type safe ...
>     }
> }
> 
> UntypedStateMachineBuilder builder = StateMachineBuilderFactory.create(
> UntypedStateMachineSample.class);
> // state machine builder not type safe anymore
> builder.externalTransition().from("D").to("A").on(TestEvent.toA);
> UntypedStateMachine fsm = builder.newStateMachine("A");
> ```

notice that  your Class  UntypedStateMachineSample  should  be  static

**Comment by yqsas** [comment] 2019-04-09 06:47
I am also getting the same error.
Because I added a constructor with arguments in my custome StateMachine，and when create it without the arguments

**Comment by cnmuc** [comment] 2019-08-04 18:44
Some error here. Tried all versions 0.2.7 -> 0.3.8. Tried sample code, also tried the code from the comments here.

**Comment by cnmuc** [comment] 2019-08-04 19:24
The problem can be reproduced by adding to pom,xml 
    <dependency>
      <groupId>com.google.collections</groupId>
      <artifactId>google-collections</artifactId>
      <version>1.0</version>
    </dependency>

**Comment by cnmuc** [comment] 2019-08-04 19:30
Opened a new issue https://github.com/hekailiang/squirrel/issues/102
